canonicalRNN_electricity:
  hyperparameters:
    context_length:
      $eval: 2 * $trial.dataset.meta.prediction_length
    epochs: 100
    forecaster_name: gluonts.model.canonical.CanonicalRNNEstimator
    freq:
      $eval: __trial__.dataset.meta.freq
    learning_rate: 0.001
    listify_dataset: 'yes'
    num_cells: 70
    num_layers: 3
    num_workers: 8
    prediction_length:
      $eval: $trial.dataset.meta.prediction_length
  image: arangatang/masterthesis:gluonts_cpu_commit_4d1a9a0
  instance: local
  name: canonicalRNN

canonicalRNN_solar_energy:
  hyperparameters:
    cardinality:
    - 137
    context_length:
      $eval: $trial.dataset.meta.prediction_length
    epochs: 100
    forecaster_name: gluonts.model.canonical.CanonicalRNNEstimator
    freq:
      $eval: __trial__.dataset.meta.freq
    learning_rate: 0.001
    listify_dataset: 'yes'
    num_cells: 50
    num_layers: 2
    num_workers: 6
    prediction_length:
      $eval: $trial.dataset.meta.prediction_length
    use_feat_static_cat: true
  image: arangatang/masterthesis:gluonts_cpu_commit_4d1a9a0
  instance: local
  name: canonicalRNN

canonicalRNN_m5:
  hyperparameters:
    cardinality:
    - 3049
    - 7
    - 3
    - 10
    - 3
    context_length:
      $eval: 2 * $trial.dataset.meta.prediction_length
    epochs: 100
    forecaster_name: gluonts.model.canonical.CanonicalRNNEstimator
    freq:
      $eval: __trial__.dataset.meta.freq
    learning_rate: 0.001
    listify_dataset: 'yes'
    num_cells: 50
    num_layers: 2
    num_workers: 6
    prediction_length:
      $eval: $trial.dataset.meta.prediction_length
    use_feat_static_cat: true
  image: arangatang/masterthesis:gluonts_cpu_commit_4d1a9a0
  instance: local
  name: canonicalRNN

canonicalRNN_m4_daily:
  hyperparameters:
    cardinality:
    - 4227
    context_length:
      $eval: $trial.dataset.meta.prediction_length
    epochs: 100
    forecaster_name: gluonts.model.canonical.CanonicalRNNEstimator
    freq:
      $eval: __trial__.dataset.meta.freq
    learning_rate: 0.001
    listify_dataset: 'yes'
    num_cells: 70
    num_layers: 3
    num_workers: 6
    prediction_length:
      $eval: $trial.dataset.meta.prediction_length
    use_feat_static_cat: true
  image: arangatang/masterthesis:gluonts_cpu_commit_4d1a9a0
  instance: local
  name: canonicalRNN
