base:
    image: arangatang/masterthesis:gluonts_cpu_commit_4d1a9a0

SimpleFeedForward:
    $from: base
    name: SimpleFeedForward
    hyperparameters:
        epochs: 1
        freq:
            $eval: $trial.dataset.meta.freq
        prediction_length:
            $eval: 2 * $trial.dataset.meta.prediction_length
        context_length:
            $eval: 2 * $trial.algorithm.hyperparameters.prediction_length
        forecaster_name: gluonts.model.simple_feedforward.SimpleFeedForwardEstimator    
    instance: local

SimpleFeedForward_electricity:
    $from: SimpleFeedForward
    hyperparameters:
        epochs: 5

deepar:
    $from: base
    name: deepar
    hyperparameters:
        epochs: 1
        freq:
            $eval: $trial.dataset.meta.freq
        prediction_length:
            $eval: 2 * $trial.dataset.meta.prediction_length
        context_length:
            $eval: 2 * $trial.algorithm.hyperparameters.prediction_length
        forecaster_name: gluonts.model.deepar.DeepAREstimator    
    instance: local
