base:
  image: gluonts:R
  instance: local
  hyperparameters:
    prediction_length:
      $eval: $trial.dataset.meta.prediction_length
    freq:
      $eval: $trial.dataset.meta.freq
  name: 
    $eval: $trial.algorithm.hyperparameters.forecaster_name.split('.')[-1]

arima:
  $from: base
  hyperparameters:
    forecaster_name: gluonts.model.r_forecast.RForecastPredictor
    method_name: arima


ets:
  $from: base
  hyperparameters:
    forecaster_name: gluonts.model.r_forecast.RForecastPredictor
    method_name: ets

    
thetaf:
  $from: base
  hyperparameters:
    forecaster_name: gluonts.model.r_forecast.RForecastPredictor
    method_name: thetaf
