simplefeedforward_electricity:
  hyperparameters:
    context_length:
      $eval: $trial.dataset.meta.prediction_length
    epochs: 100
    forecaster_name: gluonts.model.simple_feedforward.SimpleFeedForwardEstimator
    freq:
      $eval: __trial__.dataset.meta.freq
    learning_rate: 0.001
    listify_dataset: 'yes'
    num_hidden_dimensions:
    - 60
    - 60
    num_workers: 8
    prediction_length:
      $eval: $trial.dataset.meta.prediction_length
  image: arangatang/masterthesis:gluonts_commit_4d1a9a0
  instance: local
  name: simplefeedforward

simplefeedforward_solar_energy:
  hyperparameters:
    cardinality:
    - 137
    context_length:
      $eval: $trial.dataset.meta.prediction_length
    epochs: 100
    forecaster_name: gluonts.model.simple_feedforward.SimpleFeedForwardEstimator
    freq:
      $eval: __trial__.dataset.meta.freq
    learning_rate: 0.001
    listify_dataset: 'yes'
    num_hidden_dimensions:
    - 40
    - 40
    num_workers: 6
    prediction_length:
      $eval: $trial.dataset.meta.prediction_length
    use_feat_static_cat: true
  image: arangatang/masterthesis:gluonts_commit_4d1a9a0
  instance: local
  name: simplefeedforward

simplefeedforward_m5:
  hyperparameters:
    cardinality:
    - 3049
    - 7
    - 3
    - 10
    - 3
    context_length:
      $eval: $trial.dataset.meta.prediction_length
    epochs: 100
    forecaster_name: gluonts.model.simple_feedforward.SimpleFeedForwardEstimator
    freq:
      $eval: __trial__.dataset.meta.freq
    learning_rate: 0.001
    listify_dataset: 'yes'
    num_hidden_dimensions:
    - 60
    - 60
    num_workers: 6
    prediction_length:
      $eval: $trial.dataset.meta.prediction_length
    use_feat_static_cat: true
  image: arangatang/masterthesis:gluonts_commit_4d1a9a0
  instance: local
  name: simplefeedforward

simplefeedforward_m4_daily:
  hyperparameters:
    cardinality:
    - 4227
    context_length:
      $eval: $trial.dataset.meta.prediction_length
    epochs: 100
    forecaster_name: gluonts.model.simple_feedforward.SimpleFeedForwardEstimator
    freq:
      $eval: __trial__.dataset.meta.freq
    learning_rate: 0.001
    listify_dataset: 'yes'
    num_hidden_dimensions:
    - 40
    - 40
    num_workers: 6
    prediction_length:
      $eval: $trial.dataset.meta.prediction_length
    use_feat_static_cat: true
  image: arangatang/masterthesis:gluonts_commit_4d1a9a0
  instance: local
  name: simplefeedforward
