NBEATSEnsembleEstimator_electricity:
  hyperparameters:
    context_length:
      $eval: 2 * $trial.dataset.meta.prediction_length
    epochs: 100
    forecaster_name: gluonts.model.n_beats.NBEATSEstimator
    freq:
      $eval: __trial__.dataset.meta.freq
    learning_rate: 0.001
    listify_dataset: 'yes'
    loss_function: MASE
    meta_bagging_size: 10
    num_blocks:
    - 1
    num_stacks: 30
    num_workers: 8
    prediction_length:
      $eval: $trial.dataset.meta.prediction_length
    widths:
    - 256
  image: arangatang/masterthesis:gluonts_cpu_commit_4d1a9a0
  instance: local
  name: NBEATSEnsembleEstimator

NBEATSEnsembleEstimator_solar_energy:
  hyperparameters:
    cardinality:
    - 137
    context_length:
      $eval: $trial.dataset.meta.prediction_length
    epochs: 100
    forecaster_name: gluonts.model.n_beats.NBEATSEstimator
    freq:
      $eval: __trial__.dataset.meta.freq
    learning_rate: 0.001
    listify_dataset: 'yes'
    loss_function: MASE
    meta_bagging_size: 5
    num_blocks:
    - 1
    num_stacks: 20
    num_workers: 6
    prediction_length:
      $eval: $trial.dataset.meta.prediction_length
    use_feat_static_cat: true
    widths:
    - 512
  image: arangatang/masterthesis:gluonts_cpu_commit_4d1a9a0
  instance: local
  name: NBEATSEnsembleEstimator

NBEATSEnsembleEstimator_m5:
  hyperparameters:
    cardinality:
    - 3049
    - 7
    - 3
    - 10
    - 3
    context_length:
      $eval: 2 * $trial.dataset.meta.prediction_length
    epochs: 100
    forecaster_name: gluonts.model.n_beats.NBEATSEstimator
    freq:
      $eval: __trial__.dataset.meta.freq
    learning_rate: 0.001
    listify_dataset: 'yes'
    loss_function: MASE
    meta_bagging_size: 5
    num_blocks:
    - 1
    num_stacks: 20
    num_workers: 8
    prediction_length:
      $eval: $trial.dataset.meta.prediction_length
    use_feat_static_cat: true
    widths:
    - 512
  image: arangatang/masterthesis:gluonts_cpu_commit_4d1a9a0
  instance: local
  name: NBEATSEnsembleEstimator

NBEATSEnsembleEstimator_m4_daily:
  hyperparameters:
    cardinality:
    - 4227
    context_length:
      $eval: $trial.dataset.meta.prediction_length
    epochs: 100
    forecaster_name: gluonts.model.n_beats.NBEATSEstimator
    freq:
      $eval: __trial__.dataset.meta.freq
    learning_rate: 0.01
    listify_dataset: 'yes'
    loss_function: MASE
    meta_bagging_size: 10
    num_blocks:
    - 2
    num_stacks: 20
    num_workers: 6
    prediction_length:
      $eval: $trial.dataset.meta.prediction_length
    use_feat_static_cat: true
    widths:
    - 512
  image: arangatang/masterthesis:gluonts_cpu_commit_4d1a9a0
  instance: local
  name: NBEATSEnsembleEstimator
