deepar_electricity:
  hyperparameters:
    context_length:
      $eval: 2 * $trial.dataset.meta.prediction_length
    epochs: 100
    forecaster_name: gluonts.model.deepar.DeepAREstimator
    freq:
      $eval: __trial__.dataset.meta.freq
    learning_rate: 0.001
    listify_dataset: 'yes'
    num_cells: 40
    num_layers: 1
    num_workers: 8
    prediction_length:
      $eval: $trial.dataset.meta.prediction_length
  image: arangatang/masterthesis:gluonts_cpu_commit_4d1a9a0
  instance: local
  name: deepar

  deepar_solar_energy:
  hyperparameters:
    cardinality:
    - 137
    context_length:
      $eval: $trial.dataset.meta.prediction_length
    epochs: 100
    forecaster_name: gluonts.model.deepar.DeepAREstimator
    freq:
      $eval: __trial__.dataset.meta.freq
    learning_rate: 0.01
    listify_dataset: 'yes'
    num_cells: 20
    num_layers: 1
    num_workers: 6
    prediction_length:
      $eval: $trial.dataset.meta.prediction_length
    use_feat_static_cat: true
  image: arangatang/masterthesis:gluonts_cpu_commit_4d1a9a0
  instance: local
  name: deepar

deepar_m5:
  hyperparameters:
    cardinality:
    - 3049
    - 7
    - 3
    - 10
    - 3
    context_length:
      $eval: $trial.dataset.meta.prediction_length
    epochs: 100
    forecaster_name: gluonts.model.deepar.DeepAREstimator
    freq:
      $eval: __trial__.dataset.meta.freq
    learning_rate: 0.001
    listify_dataset: 'yes'
    num_cells: 40
    num_layers: 3
    num_workers: 6
    prediction_length:
      $eval: $trial.dataset.meta.prediction_length
    use_feat_static_cat: true
  image: arangatang/masterthesis:gluonts_cpu_commit_4d1a9a0
  instance: local
  name: deepar

deepar_m4_daily:
  hyperparameters:
    cardinality:
    - 4227
    context_length:
      $eval: $trial.dataset.meta.prediction_length
    epochs: 100
    forecaster_name: gluonts.model.deepar.DeepAREstimator
    freq:
      $eval: __trial__.dataset.meta.freq
    learning_rate: 0.001
    listify_dataset: 'yes'
    num_cells: 60
    num_layers: 1
    num_workers: 6
    prediction_length:
      $eval: $trial.dataset.meta.prediction_length
    use_feat_static_cat: true
  image: arangatang/masterthesis:gluonts_cpu_commit_4d1a9a0
  instance: local
  name: deepar

deepFactorEstimator_electricity:
  hyperparameters:
    context_length:
      $eval: 2 * $trial.dataset.meta.prediction_length
    epochs: 100
    forecaster_name: gluonts.model.deep_factor.DeepFactorEstimator
    freq:
      $eval: __trial__.dataset.meta.freq
    learning_rate: 0.0001
    listify_dataset: 'yes'
    num_factors: 10
    num_hidden_global: 50
    num_hidden_local: 3
    num_layers_global: 2
    num_layers_local: 1
    num_workers: 8
    prediction_length:
      $eval: $trial.dataset.meta.prediction_length
  image: arangatang/masterthesis:gluonts_cpu_commit_4d1a9a0
  instance: local
  name: deepFactorEstimator

deepFactorEstimator_solar_energy:
  hyperparameters:
    cardinality:
    - 137
    context_length:
      $eval: $trial.dataset.meta.prediction_length
    epochs: 100
    forecaster_name: gluonts.model.deep_factor.DeepFactorEstimator
    freq:
      $eval: __trial__.dataset.meta.freq
    learning_rate: 0.0001
    listify_dataset: 'yes'
    num_factors: 7
    num_hidden_global: 50
    num_hidden_local: 5
    num_layers_global: 1
    num_layers_local: 1
    num_workers: 6
    prediction_length:
      $eval: $trial.dataset.meta.prediction_length
    use_feat_static_cat: true
  image: arangatang/masterthesis:gluonts_cpu_commit_4d1a9a0
  instance: local
  name: deepFactorEstimator

deepFactorEstimator_m5:
  hyperparameters:
    cardinality:
    - 3049
    - 7
    - 3
    - 10
    - 3
    context_length:
      $eval: $trial.dataset.meta.prediction_length
    epochs: 100
    forecaster_name: gluonts.model.deep_factor.DeepFactorEstimator
    freq:
      $eval: __trial__.dataset.meta.freq
    learning_rate: 0.001
    listify_dataset: 'yes'
    num_factors: 7
    num_hidden_global: 30
    num_hidden_local: 5
    num_layers_global: 2
    num_layers_local: 1
    num_workers: 6
    prediction_length:
      $eval: $trial.dataset.meta.prediction_length
    use_feat_static_cat: true
  image: arangatang/masterthesis:gluonts_cpu_commit_4d1a9a0
  instance: local
  name: deepFactorEstimator

deepFactorEstimator_m4_daily:
  hyperparameters:
    cardinality:
    - 4227
    context_length:
      $eval: $trial.dataset.meta.prediction_length
    epochs: 100
    forecaster_name: gluonts.model.deep_factor.DeepFactorEstimator
    freq:
      $eval: __trial__.dataset.meta.freq
    learning_rate: 0.0001
    listify_dataset: 'yes'
    num_factors: 7
    num_hidden_global: 50
    num_hidden_local: 5
    num_layers_global: 1
    num_layers_local: 2
    num_workers: 6
    prediction_length:
      $eval: $trial.dataset.meta.prediction_length
    use_feat_static_cat: true
  image: arangatang/masterthesis:gluonts_cpu_commit_4d1a9a0
  instance: local
  name: deepFactorEstimator

canonicalRNN_electricity:
  hyperparameters:
    context_length:
      $eval: 2 * $trial.dataset.meta.prediction_length
    epochs: 100
    forecaster_name: gluonts.model.canonical.CanonicalRNNEstimator
    freq:
      $eval: __trial__.dataset.meta.freq
    learning_rate: 0.001
    listify_dataset: 'yes'
    num_cells: 70
    num_layers: 3
    num_workers: 8
    prediction_length:
      $eval: $trial.dataset.meta.prediction_length
  image: arangatang/masterthesis:gluonts_cpu_commit_4d1a9a0
  instance: local
  name: canonicalRNN

canonicalRNN_solar_energy:
  hyperparameters:
    cardinality:
    - 137
    context_length:
      $eval: $trial.dataset.meta.prediction_length
    epochs: 100
    forecaster_name: gluonts.model.canonical.CanonicalRNNEstimator
    freq:
      $eval: __trial__.dataset.meta.freq
    learning_rate: 0.001
    listify_dataset: 'yes'
    num_cells: 50
    num_layers: 2
    num_workers: 6
    prediction_length:
      $eval: $trial.dataset.meta.prediction_length
    use_feat_static_cat: true
  image: arangatang/masterthesis:gluonts_cpu_commit_4d1a9a0
  instance: local
  name: canonicalRNN

canonicalRNN_m5:
  hyperparameters:
    cardinality:
    - 3049
    - 7
    - 3
    - 10
    - 3
    context_length:
      $eval: 2 * $trial.dataset.meta.prediction_length
    epochs: 100
    forecaster_name: gluonts.model.canonical.CanonicalRNNEstimator
    freq:
      $eval: __trial__.dataset.meta.freq
    learning_rate: 0.001
    listify_dataset: 'yes'
    num_cells: 50
    num_layers: 2
    num_workers: 6
    prediction_length:
      $eval: $trial.dataset.meta.prediction_length
    use_feat_static_cat: true
  image: arangatang/masterthesis:gluonts_cpu_commit_4d1a9a0
  instance: local
  name: canonicalRNN

canonicalRNN_m4_daily:
  hyperparameters:
    cardinality:
    - 4227
    context_length:
      $eval: $trial.dataset.meta.prediction_length
    epochs: 100
    forecaster_name: gluonts.model.canonical.CanonicalRNNEstimator
    freq:
      $eval: __trial__.dataset.meta.freq
    learning_rate: 0.001
    listify_dataset: 'yes'
    num_cells: 70
    num_layers: 3
    num_workers: 6
    prediction_length:
      $eval: $trial.dataset.meta.prediction_length
    use_feat_static_cat: true
  image: arangatang/masterthesis:gluonts_cpu_commit_4d1a9a0
  instance: local
  name: canonicalRNN

simplefeedforward_electricity:
  hyperparameters:
    context_length:
      $eval: $trial.dataset.meta.prediction_length
    epochs: 100
    forecaster_name: gluonts.model.simple_feedforward.SimpleFeedForwardEstimator
    freq:
      $eval: __trial__.dataset.meta.freq
    learning_rate: 0.001
    listify_dataset: 'yes'
    num_hidden_dimensions:
    - 60
    - 60
    num_workers: 8
    prediction_length:
      $eval: $trial.dataset.meta.prediction_length
  image: arangatang/masterthesis:gluonts_cpu_commit_4d1a9a0
  instance: local
  name: simplefeedforward

simplefeedforward_solar_energy:
  hyperparameters:
    cardinality:
    - 137
    context_length:
      $eval: $trial.dataset.meta.prediction_length
    epochs: 100
    forecaster_name: gluonts.model.simple_feedforward.SimpleFeedForwardEstimator
    freq:
      $eval: __trial__.dataset.meta.freq
    learning_rate: 0.001
    listify_dataset: 'yes'
    num_hidden_dimensions:
    - 40
    - 40
    num_workers: 6
    prediction_length:
      $eval: $trial.dataset.meta.prediction_length
    use_feat_static_cat: true
  image: arangatang/masterthesis:gluonts_cpu_commit_4d1a9a0
  instance: local
  name: simplefeedforward

simplefeedforward_m5:
  hyperparameters:
    cardinality:
    - 3049
    - 7
    - 3
    - 10
    - 3
    context_length:
      $eval: $trial.dataset.meta.prediction_length
    epochs: 100
    forecaster_name: gluonts.model.simple_feedforward.SimpleFeedForwardEstimator
    freq:
      $eval: __trial__.dataset.meta.freq
    learning_rate: 0.001
    listify_dataset: 'yes'
    num_hidden_dimensions:
    - 60
    - 60
    num_workers: 6
    prediction_length:
      $eval: $trial.dataset.meta.prediction_length
    use_feat_static_cat: true
  image: arangatang/masterthesis:gluonts_cpu_commit_4d1a9a0
  instance: local
  name: simplefeedforward

simplefeedforward_m4_daily:
  hyperparameters:
    cardinality:
    - 4227
    context_length:
      $eval: $trial.dataset.meta.prediction_length
    epochs: 100
    forecaster_name: gluonts.model.simple_feedforward.SimpleFeedForwardEstimator
    freq:
      $eval: __trial__.dataset.meta.freq
    learning_rate: 0.001
    listify_dataset: 'yes'
    num_hidden_dimensions:
    - 40
    - 40
    num_workers: 6
    prediction_length:
      $eval: $trial.dataset.meta.prediction_length
    use_feat_static_cat: true
  image: arangatang/masterthesis:gluonts_cpu_commit_4d1a9a0
  instance: local
  name: simplefeedforward

NBEATSEnsembleEstimator_electricity:
  hyperparameters:
    context_length:
      $eval: 2 * $trial.dataset.meta.prediction_length
    epochs: 100
    forecaster_name: gluonts.model.n_beats.NBEATSEstimator
    freq:
      $eval: __trial__.dataset.meta.freq
    learning_rate: 0.001
    listify_dataset: 'yes'
    loss_function: MASE
    meta_bagging_size: 10
    num_blocks:
    - 1
    num_stacks: 30
    num_workers: 8
    prediction_length:
      $eval: $trial.dataset.meta.prediction_length
    widths:
    - 256
  image: arangatang/masterthesis:gluonts_cpu_commit_4d1a9a0
  instance: local
  name: NBEATSEnsembleEstimator

NBEATSEnsembleEstimator_solar_energy:
  hyperparameters:
    cardinality:
    - 137
    context_length:
      $eval: $trial.dataset.meta.prediction_length
    epochs: 100
    forecaster_name: gluonts.model.n_beats.NBEATSEstimator
    freq:
      $eval: __trial__.dataset.meta.freq
    learning_rate: 0.001
    listify_dataset: 'yes'
    loss_function: MASE
    meta_bagging_size: 5
    num_blocks:
    - 1
    num_stacks: 20
    num_workers: 6
    prediction_length:
      $eval: $trial.dataset.meta.prediction_length
    use_feat_static_cat: true
    widths:
    - 512
  image: arangatang/masterthesis:gluonts_cpu_commit_4d1a9a0
  instance: local
  name: NBEATSEnsembleEstimator

NBEATSEnsembleEstimator_m5:
  hyperparameters:
    cardinality:
    - 3049
    - 7
    - 3
    - 10
    - 3
    context_length:
      $eval: 2 * $trial.dataset.meta.prediction_length
    epochs: 100
    forecaster_name: gluonts.model.n_beats.NBEATSEstimator
    freq:
      $eval: __trial__.dataset.meta.freq
    learning_rate: 0.001
    listify_dataset: 'yes'
    loss_function: MASE
    meta_bagging_size: 5
    num_blocks:
    - 1
    num_stacks: 20
    num_workers: 8
    prediction_length:
      $eval: $trial.dataset.meta.prediction_length
    use_feat_static_cat: true
    widths:
    - 512
  image: arangatang/masterthesis:gluonts_cpu_commit_4d1a9a0
  instance: local
  name: NBEATSEnsembleEstimator

NBEATSEnsembleEstimator_m4_daily:
  hyperparameters:
    cardinality:
    - 4227
    context_length:
      $eval: $trial.dataset.meta.prediction_length
    epochs: 100
    forecaster_name: gluonts.model.n_beats.NBEATSEstimator
    freq:
      $eval: __trial__.dataset.meta.freq
    learning_rate: 0.01
    listify_dataset: 'yes'
    loss_function: MASE
    meta_bagging_size: 10
    num_blocks:
    - 2
    num_stacks: 20
    num_workers: 6
    prediction_length:
      $eval: $trial.dataset.meta.prediction_length
    use_feat_static_cat: true
    widths:
    - 512
  image: arangatang/masterthesis:gluonts_cpu_commit_4d1a9a0
  instance: local
  name: NBEATSEnsembleEstimator

MQRNNEstimator_electricity:
  hyperparameters:
    context_length:
      $eval: $trial.dataset.meta.prediction_length
    epochs: 100
    forecaster_name: gluonts.model.seq2seq.MQRNNEstimator
    freq:
      $eval: __trial__.dataset.meta.freq
    learning_rate: 0.001
    listify_dataset: 'yes'
    mlp_final_dim: 30
    mlp_hidden_dimension_seq:
    - 2
    num_workers: 8
    prediction_length:
      $eval: $trial.dataset.meta.prediction_length
  image: arangatang/masterthesis:gluonts_cpu_commit_4d1a9a0
  instance: local
  name: MQRNNEstimator

MQRNNEstimator_solar_energy:
  hyperparameters:
    cardinality:
    - 137
    context_length:
      $eval: 2 * $trial.dataset.meta.prediction_length
    epochs: 100
    forecaster_name: gluonts.model.seq2seq.MQRNNEstimator
    freq:
      $eval: __trial__.dataset.meta.freq
    learning_rate: 0.001
    listify_dataset: 'yes'
    mlp_final_dim: 10
    mlp_hidden_dimension_seq:
    - 2
    num_workers: 6
    prediction_length:
      $eval: $trial.dataset.meta.prediction_length
    use_feat_static_cat: true
  image: arangatang/masterthesis:gluonts_cpu_commit_4d1a9a0
  instance: local
  name: MQRNNEstimator

MQRNNEstimator_m5:
  hyperparameters:
    cardinality:
    - 3049
    - 7
    - 3
    - 10
    - 3
    context_length:
      $eval: $trial.dataset.meta.prediction_length
    epochs: 100
    forecaster_name: gluonts.model.seq2seq.MQRNNEstimator
    freq:
      $eval: __trial__.dataset.meta.freq
    learning_rate: 0.01
    listify_dataset: 'yes'
    mlp_final_dim: 20
    mlp_hidden_dimension_seq:
    - 2
    num_workers: 6
    prediction_length:
      $eval: $trial.dataset.meta.prediction_length
    use_feat_static_cat: true
  image: arangatang/masterthesis:gluonts_cpu_commit_4d1a9a0
  instance: local
  name: MQRNNEstimator

MQRNNEstimator_m4_daily:
  hyperparameters:
    cardinality:
    - 4227
    context_length:
      $eval: $trial.dataset.meta.prediction_length
    epochs: 100
    forecaster_name: gluonts.model.seq2seq.MQRNNEstimator
    freq:
      $eval: __trial__.dataset.meta.freq
    learning_rate: 0.001
    listify_dataset: 'yes'
    mlp_final_dim: 10
    mlp_hidden_dimension_seq:
    - 2
    - 2
    num_workers: 6
    prediction_length:
      $eval: $trial.dataset.meta.prediction_length
    use_feat_static_cat: true
  image: arangatang/masterthesis:gluonts_cpu_commit_4d1a9a0
  instance: local
  name: MQRNNEstimator

TransformerEstimator_electricity:
  hyperparameters:
    context_length:
      $eval: 2 * $trial.dataset.meta.prediction_length
    embedding_dimension: 20
    epochs: 100
    forecaster_name: gluonts.model.transformer.TransformerEstimator
    freq:
      $eval: __trial__.dataset.meta.freq
    inner_ff_dim_scale: 6
    learning_rate: 0.01
    listify_dataset: 'yes'
    model_dim: 32
    num_workers: 8
    prediction_length:
      $eval: $trial.dataset.meta.prediction_length
  image: arangatang/masterthesis:gluonts_cpu_commit_4d1a9a0
  instance: local
  name: TransformerEstimator

TransformerEstimator_solar_energy:
  hyperparameters:
    cardinality:
    - 137
    context_length:
      $eval: $trial.dataset.meta.prediction_length
    embedding_dimension: 10
    epochs: 100
    forecaster_name: gluonts.model.transformer.TransformerEstimator
    freq:
      $eval: __trial__.dataset.meta.freq
    inner_ff_dim_scale: 6
    learning_rate: 0.001
    listify_dataset: 'yes'
    model_dim: 64
    num_workers: 6
    prediction_length:
      $eval: $trial.dataset.meta.prediction_length
    use_feat_static_cat: true
  image: arangatang/masterthesis:gluonts_cpu_commit_4d1a9a0
  instance: local
  name: TransformerEstimator

TransformerEstimator_m5:
  hyperparameters:
    cardinality:
    - 3049
    - 7
    - 3
    - 10
    - 3
    context_length:
      $eval: $trial.dataset.meta.prediction_length
    embedding_dimension: 10
    epochs: 100
    forecaster_name: gluonts.model.transformer.TransformerEstimator
    freq:
      $eval: __trial__.dataset.meta.freq
    inner_ff_dim_scale: 4
    learning_rate: 0.0001
    listify_dataset: 'yes'
    model_dim: 64
    num_workers: 6
    prediction_length:
      $eval: $trial.dataset.meta.prediction_length
    use_feat_static_cat: true
  image: arangatang/masterthesis:gluonts_cpu_commit_4d1a9a0
  instance: local
  name: TransformerEstimator

TransformerEstimator_m4_daily:
  hyperparameters:
    cardinality:
    - 4227
    context_length:
      $eval: 2 * $trial.dataset.meta.prediction_length
    embedding_dimension: 10
    epochs: 100
    forecaster_name: gluonts.model.transformer.TransformerEstimator
    freq:
      $eval: __trial__.dataset.meta.freq
    inner_ff_dim_scale: 4
    learning_rate: 0.001
    listify_dataset: 'yes'
    model_dim: 16
    num_workers: 6
    prediction_length:
      $eval: $trial.dataset.meta.prediction_length
    use_feat_static_cat: true
  image: arangatang/masterthesis:gluonts_cpu_commit_4d1a9a0
  instance: local
  name: TransformerEstimator

MQCNNEstimator_electricity:
  hyperparameters:
    context_length:
      $eval: 2 * $trial.dataset.meta.prediction_length
    epochs: 100
    forecaster_name: gluonts.model.seq2seq.MQCNNEstimator
    freq:
      $eval: __trial__.dataset.meta.freq
    learning_rate: 0.0001
    listify_dataset: 'yes'
    mlp_final_dim: 20
    mlp_hidden_dimension_seq: []
    num_workers: 8
    prediction_length:
      $eval: $trial.dataset.meta.prediction_length
  image: arangatang/masterthesis:gluonts_cpu_commit_4d1a9a0
  instance: local
  name: MQCNNEstimator

MQCNNEstimator_solar_energy:
  hyperparameters:
    cardinality:
    - 137
    context_length:
      $eval: 2 * $trial.dataset.meta.prediction_length
    epochs: 100
    forecaster_name: gluonts.model.seq2seq.MQCNNEstimator
    freq:
      $eval: __trial__.dataset.meta.freq
    learning_rate: 0.01
    listify_dataset: 'yes'
    mlp_final_dim: 20
    mlp_hidden_dimension_seq:
    - 2
    num_workers: 6
    prediction_length:
      $eval: $trial.dataset.meta.prediction_length
    use_feat_static_cat: true
  image: arangatang/masterthesis:gluonts_cpu_commit_4d1a9a0
  instance: local
  name: MQCNNEstimator

MQCNNEstimator_m4_daily:
  hyperparameters:
    cardinality:
    - 4227
    context_length:
      $eval: 2 * $trial.dataset.meta.prediction_length
    epochs: 100
    forecaster_name: gluonts.model.seq2seq.MQCNNEstimator
    freq:
      $eval: __trial__.dataset.meta.freq
    learning_rate: 0.0001
    listify_dataset: 'yes'
    mlp_final_dim: 10
    mlp_hidden_dimension_seq:
    - 1
    num_workers: 6
    prediction_length:
      $eval: $trial.dataset.meta.prediction_length
    use_feat_static_cat: true
  image: arangatang/masterthesis:gluonts_cpu_commit_4d1a9a0
  instance: local
  name: MQCNNEstimator